# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Timing 38-35}  -string {{INFO: [Timing 38-35] Done setting XDC timing constraints.}}  -suppress 
set_msg_config  -ruleid {10}  -id {Common 17-83}  -string {{INFO: [Common 17-83] Releasing license: Synthesis}}  -suppress 
set_msg_config  -ruleid {100}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][-4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {101}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[19,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {102}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][-5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {103}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[18,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {104}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[18,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {105}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[18,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {106}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[17,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {107}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[17,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {108}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[16,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {109}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[16,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {11}  -id {Place 30-99}  -string {{ERROR: [Place 30-99] Placer failed with error: 'IO Clock Placer failed'
Please review all ERROR, CRITICAL WARNING, and WARNING messages during placement to understand the cause for failure.}}  -suppress 
set_msg_config  -ruleid {110}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[16,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {111}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[15,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {112}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[15,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {113}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[15,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {114}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[14,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {115}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[14,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {116}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[13,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {117}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[13,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {118}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[13,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {119}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[12,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {12}  -id {Synth 8-5545}  -string {{INFO: [Synth 8-5545] ROM "signature_weight_t_reg[0,0]" won't be mapped to RAM because address size (31) is larger than maximum supported(25)}}  -suppress 
set_msg_config  -ruleid {120}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[12,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {121}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[12,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {122}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[11,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {123}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[11,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {124}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[11,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {125}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[10,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {126}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[10,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {127}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[10,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {128}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[9,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {129}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[9,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {13}  -id {Synth 8-5845}  -string {{INFO: [Synth 8-5845] Not enough pipeline registers after wide multiplier. Recommended levels of pipeline registers is 2 [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_pkg_c.vhd:2505]}}  -suppress 
set_msg_config  -ruleid {130}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[9,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {131}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[8,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {132}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[8,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {133}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[8,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {134}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[7,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {135}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[7,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {136}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[7,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {137}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[6,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {138}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[6,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {139}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[6,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {14}  -id {Synth 8-3491}  -string {{INFO: [Synth 8-3491] module 'neuro_bio' declared at '/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd:13' bound to instance 'U1' of component 'neuro_bio' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/top_level.vhd:121]}}  -suppress 
set_msg_config  -ruleid {140}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[5,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {141}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[5,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {142}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[5,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {143}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[4,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {144}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[4,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {145}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[4,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {146}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[3,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {147}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[3,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {148}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[2,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {149}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][-6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {15}  -id {HDL 9-1061}  -string {{INFO: [HDL 9-1061] Parsing VHDL file "/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/MATH_REAL.vhd" into library neuronal [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/MATH_REAL.vhd:1]}}  -suppress 
set_msg_config  -ruleid {150}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][0]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {151}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][10]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {152}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][11]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {153}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][12]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {154}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][13]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {155}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][14]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {156}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][15]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {157}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {158}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {159}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {16}  -string {{Command: place_design}}  -suppress 
set_msg_config  -ruleid {160}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {161}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {162}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {163}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][7]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {164}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][8]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {165}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][9]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {166}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][-1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {167}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][-2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {168}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][-3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {169}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][-4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {17}  -id {Common 17-1381}  -string {{INFO: [Common 17-1381] The checkpoint '/users/tareelou/neural_network_sfixed/neural_network_sfixed.runs/synth_1/top_level.dcp' has been generated.}}  -suppress 
set_msg_config  -ruleid {170}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][-5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {171}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][-6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {172}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][0]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {173}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][10]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {174}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][11]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {175}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][12]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {176}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][13]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {177}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][14]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {178}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][15]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {179}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {18}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (flag_t_reg[30]) is unused and will be removed from module neuro_bio.}}  -suppress 
set_msg_config  -ruleid {180}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {181}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {182}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {183}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {184}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {185}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][7]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {186}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][8]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {187}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,1][9]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {188}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][-1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {189}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][-2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {19}  -id {Place 30-611}  -string {{INFO: [Place 30-611] Multithreading enabled for place_design using a maximum of 8 CPUs}}  -suppress 
set_msg_config  -ruleid {190}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][-3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {191}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][-4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {192}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][-5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {193}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][-6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {194}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][0]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {195}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][10]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {196}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][11]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {197}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][12]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {198}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][13]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {199}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][14]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {2}  -id {Synth 8-5580}  -string {{INFO: [Synth 8-5580] Multithreading enabled for synth_design using a maximum of 4 processes.}}  -suppress 
set_msg_config  -ruleid {20}  -id {Common 17-1223}  -string {{INFO: [Common 17-1223] The version limit for your license is '2019.01' and will expire in -726 days. A version limit expiration means that, although you may be able to continue to use the current version of tools or IP with this license, you will not be eligible for any updates or new releases.}}  -suppress 
set_msg_config  -ruleid {200}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][15]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {201}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {202}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {203}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {204}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {205}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {206}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {207}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][7]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {208}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][8]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {209}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,2][9]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {21}  -id {Project 1-570}  -string {{INFO: [Project 1-570] Preparing netlist for logic optimization}}  -suppress 
set_msg_config  -ruleid {210}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][-1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {211}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][-2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {212}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][-3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {213}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][-4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {214}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][-5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {215}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][-6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {216}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][0]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {217}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][10]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {218}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][11]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {219}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][12]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {22}  -id {Project 1-111}  -string {{INFO: [Project 1-111] Unisim Transformation Summary:
No Unisim elements were transformed.}}  -suppress 
set_msg_config  -ruleid {220}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][13]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {221}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][14]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {222}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][15]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {223}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {224}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {225}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {226}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {227}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {228}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {229}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][7]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {23}  -id {Synth 8-638}  -string {{INFO: [Synth 8-638] synthesizing module 'top_level' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/top_level.vhd:39]}}  -suppress 
set_msg_config  -ruleid {230}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][8]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {231}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,0][9]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {232}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][-1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {233}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][-2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {234}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][-3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {235}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][-4]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {236}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][-5]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {237}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][-6]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {238}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][0]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {239}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][10]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {24}  -id {Common 17-14}  -string {{INFO: [Common 17-14] Message 'Place 30-68' appears 100 times and further instances of the messages will be disabled. Use the Tcl command set_msg_config to change the current settings.}}  -suppress 
set_msg_config  -ruleid {240}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][11]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {241}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][12]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {242}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][13]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {243}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[1,1][14]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {25}  -id {Netlist 29-28}  -string {{INFO: [Netlist 29-28] Unisim Transformation completed in 0 CPU seconds}}  -suppress 
set_msg_config  -ruleid {26}  -id {Synth 8-613}  -string {{WARNING: [Synth 8-613] shared variable will be implemented as local to architecture [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd:37]}}  -suppress 
set_msg_config  -ruleid {27}  -id {Synth 8-223}  -string {{INFO: [Synth 8-223] decloning instance 'Concurrent_loop_for_pixels[0].U1' (neuro_bio) to 'Concurrent_loop_for_pixels[1].U1'}}  -suppress 
set_msg_config  -ruleid {28}  -id {Common 17-14}  -string {{INFO: [Common 17-14] Message 'Synth 8-3331' appears 100 times and further instances of the messages will be disabled. Use the Tcl command set_msg_config to change the current settings.}}  -suppress 
set_msg_config  -ruleid {29}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[0,0]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {30}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][-1]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {31}  -id {Synth 8-3936}  -string {{WARNING: [Synth 8-3936] Found unconnected internal register 'flag_t_vector_reg' and it is trimmed from '17' to '1' bits. [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd:90]}}  -suppress 
set_msg_config  -ruleid {32}  -id {Common 17-206}  -string {{INFO: [Common 17-206] Exiting Vivado at Tue Jan 26 11:28:24 2021...}}  -suppress 
set_msg_config  -ruleid {33}  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'signature_weight_t_reg[0,0]' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:150]}}  -suppress 
set_msg_config  -ruleid {34}  -id {Device 21-403}  -string {{INFO: [Device 21-403] Loading part xc7z045ffg900-2}}  -suppress 
set_msg_config  -ruleid {35}  -id {Opt 31-138}  -string {{INFO: [Opt 31-138] Pushed 0 inverter(s) to 0 load pin(s).}}  -suppress 
set_msg_config  -ruleid {36}  -id {Vivado_Tcl 4-199}  -string {{INFO: [Vivado_Tcl 4-199] Please refer to the DRC report (report_drc) for more information.}}  -suppress 
set_msg_config  -ruleid {37}  -string {{Command: synth_design -top top_level -part xc7z045ffg900-2}}  -suppress 
set_msg_config  -ruleid {38}  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Placer could not place all instances}}  -suppress 
set_msg_config  -ruleid {39}  -id {Netlist 29-17}  -string {{INFO: [Netlist 29-17] Analyzing 11947 Unisim elements for replacement}}  -suppress 
set_msg_config  -ruleid {4}  -id {Common 17-349}  -string {{INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xc7z045'}}  -suppress 
set_msg_config  -ruleid {40}  -id {DRC 23-27}  -string {{INFO: [DRC 23-27] Running DRC with 8 threads}}  -suppress 
set_msg_config  -ruleid {41}  -id {Synth 8-3886}  -string {{INFO: [Synth 8-3886] merging instance 'U3i_4/SWM_neurons_flag_learning_reg[17,0]' (FDRE) to 'U3i_4/SWM_neurons_flag_learning_reg[3,2]'}}  -suppress 
set_msg_config  -ruleid {42}  -id {Common 17-83}  -string {{INFO: [Common 17-83] Releasing license: Implementation}}  -suppress 
set_msg_config  -ruleid {43}  -id {Chipscope 16-241}  -string {{INFO: [Chipscope 16-241] No debug cores found in the current design.
Before running the implement_debug_core command, either use the Set Up Debug wizard (GUI mode)
or use the create_debug_core and connect_debug_core Tcl commands to insert debug cores into the design.}}  -suppress 
set_msg_config  -ruleid {44}  -id {Place 30-415}  -string {{ERROR: [Place 30-415] IO Placement failed due to overutilization. This design contains 10519 I/O ports
 while the target  device: 7z045 package: ffg900, contains only 492 available user I/O. The target device has 492 usable I/O pins of which 0 are already occupied by user-locked I/Os.
 To rectify this issue:
 1. Ensure you are targeting the correct device and package.  Select a larger device or different package if necessary.
 2. Check the top-level ports of the design to ensure the correct number of ports are specified.
 3. Consider design changes to reduce the number of I/Os necessary.}}  -suppress 
set_msg_config  -ruleid {45}  -id {Synth 8-3333}  -string {{INFO: [Synth 8-3333] propagating constant 0 across sequential element (U3i_4/\SWM_neurons_flag_learning_reg[3,2] )}}  -suppress 
set_msg_config  -ruleid {46}  -id {Common 17-206}  -string {{INFO: [Common 17-206] Exiting Vivado at Tue Jan 26 11:31:23 2021...}}  -suppress 
set_msg_config  -ruleid {47}  -id {Synth 8-5559}  -string {{CRITICAL WARNING: [Synth 8-5559] multi-driven net Q is connected to constant driver, other driver is ignored [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {48}  -id {Project 1-571}  -string {{INFO: [Project 1-571] Translating synthesized netlist}}  -suppress 
set_msg_config  -ruleid {49}  -string {{Starting synth_design}}  -suppress 
set_msg_config  -ruleid {5}  -id {Synth 8-614}  -string {{WARNING: [Synth 8-614] signal 'flag_t_vector' is read in the process but is not in the sensitivity list [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd:44]}}  -suppress 
set_msg_config  -ruleid {50}  -id {HDL 9-1061}  -string {{INFO: [HDL 9-1061] Parsing VHDL file "/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_float_types_c.vhd" into library neuronal [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_float_types_c.vhd:1]}}  -suppress 
set_msg_config  -ruleid {51}  -id {Synth 8-613}  -string {{WARNING: [Synth 8-613] shared variable will be implemented as local to architecture [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd:38]}}  -suppress 
set_msg_config  -ruleid {52}  -id {Synth 8-638}  -string {{INFO: [Synth 8-638] synthesizing module 'neuro_bio' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd:30]}}  -suppress 
set_msg_config  -ruleid {53}  -id {Synth 8-614}  -string {{WARNING: [Synth 8-614] signal 'mux_table_input' is read in the process but is not in the sensitivity list [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/tree_reduction.vhd:39]}}  -suppress 
set_msg_config  -ruleid {54}  -id {Synth 8-3491}  -string {{INFO: [Synth 8-3491] module 'tree_reduction' declared at '/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/tree_reduction.vhd:18' bound to instance 'U2' of component 'tree_reduction' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/top_level.vhd:128]}}  -suppress 
set_msg_config  -ruleid {55}  -id {Synth 8-256}  -string {{INFO: [Synth 8-256] done synthesizing module 'tree_reduction' (2#1) [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/tree_reduction.vhd:34]}}  -suppress 
set_msg_config  -ruleid {56}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design spatial_working_memory has unconnected port azimuth_neurons[16][14]}}  -suppress 
set_msg_config  -ruleid {57}  -id {Synth 8-5545}  -string {{INFO: [Synth 8-5545] ROM "signature_weight_t_reg[0,1]" won't be mapped to RAM because address size (31) is larger than maximum supported(25)}}  -suppress 
set_msg_config  -ruleid {58}  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'signature_weight_t_reg[0,1]' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:150]}}  -suppress 
set_msg_config  -ruleid {59}  -id {Common 17-14}  -string {{INFO: [Common 17-14] Message 'Synth 8-5845' appears 100 times and further instances of the messages will be disabled. Use the Tcl command set_msg_config to change the current settings.}}  -suppress 
set_msg_config  -ruleid {6}  -id {Vivado_Tcl 4-198}  -string {{INFO: [Vivado_Tcl 4-198] DRC finished with 0 Errors}}  -suppress 
set_msg_config  -ruleid {60}  -id {Synth 8-223}  -string {{INFO: [Synth 8-223] decloning instance 'Concurrent_loop_for_pixels[0].U1' (neuro_bio) to 'Concurrent_loop_for_pixels[2].U1'}}  -suppress 
set_msg_config  -ruleid {61}  -id {Synth 8-3886}  -string {{INFO: [Synth 8-3886] merging instance 'U3i_4/SWM_neurons_flag_learning_reg[14,0]' (FDRE) to 'U3i_4/SWM_neurons_flag_learning_reg[3,2]'}}  -suppress 
set_msg_config  -ruleid {62}  -id {Synth 8-3333}  -string {{INFO: [Synth 8-3333] propagating constant 0 across sequential element (U3i_5/\signature_weight_t_reg[17,0][15] )}}  -suppress 
set_msg_config  -ruleid {63}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (flag_t_reg[29]) is unused and will be removed from module neuro_bio.}}  -suppress 
set_msg_config  -ruleid {64}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 2nd driver pin 'GND' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {65}  -id {Project 1-111}  -string {{INFO: [Project 1-111] Unisim Transformation Summary:
  A total of 62 instances were transformed.
  (MUXCY,XORCY) => CARRY4: 2 instances
  LD => LDCE: 60 instances}}  -suppress 
set_msg_config  -ruleid {66}  -string {{Attempting to get a license for feature 'Implementation' and/or device 'xc7z045'}}  -suppress 
set_msg_config  -ruleid {67}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][-2]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {68}  -id {HDL 9-1061}  -string {{INFO: [HDL 9-1061] Parsing VHDL file "/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_pkg_c.vhd" into library neuronal [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_pkg_c.vhd:1]}}  -suppress 
set_msg_config  -ruleid {69}  -id {Synth 8-613}  -string {{WARNING: [Synth 8-613] shared variable will be implemented as local to architecture [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd:39]}}  -suppress 
set_msg_config  -ruleid {7}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design spatial_working_memory has unconnected port azimuth_neurons[16][15]}}  -suppress 
set_msg_config  -ruleid {70}  -id {Synth 8-3491}  -string {{INFO: [Synth 8-3491] module 'spatial_working_memory' declared at '/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:16' bound to instance 'U3' of component 'spatial_working_memory' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/top_level.vhd:133]}}  -suppress 
set_msg_config  -ruleid {71}  -id {Synth 8-638}  -string {{INFO: [Synth 8-638] synthesizing module 'tree_reduction' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/tree_reduction.vhd:34]}}  -suppress 
set_msg_config  -ruleid {72}  -id {Synth 8-256}  -string {{INFO: [Synth 8-256] done synthesizing module 'spatial_working_memory' (3#1) [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:39]}}  -suppress 
set_msg_config  -ruleid {73}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design spatial_working_memory has unconnected port azimuth_neurons[16][13]}}  -suppress 
set_msg_config  -ruleid {74}  -string {{Attempting to get a license for feature 'Synthesis' and/or device 'xc7z045'}}  -suppress 
set_msg_config  -ruleid {75}  -id {Synth 8-5545}  -string {{INFO: [Synth 8-5545] ROM "signature_weight_t_reg[0,2]" won't be mapped to RAM because address size (31) is larger than maximum supported(25)}}  -suppress 
set_msg_config  -ruleid {76}  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'signature_weight_t_reg[0,2]' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:150]}}  -suppress 
set_msg_config  -ruleid {77}  -id {Synth 8-223}  -string {{INFO: [Synth 8-223] decloning instance 'Concurrent_loop_for_pixels[0].U1' (neuro_bio) to 'Concurrent_loop_for_pixels[3].U1'}}  -suppress 
set_msg_config  -ruleid {78}  -id {Synth 8-3886}  -string {{INFO: [Synth 8-3886] merging instance 'U3i_5/signature_weight_t_reg[17,0][-6]' (LD) to 'U3i_5/signature_weight_t_reg[17,0][15]'}}  -suppress 
set_msg_config  -ruleid {79}  -id {Synth 8-3333}  -string {{INFO: [Synth 8-3333] propagating constant 0 across sequential element (U3i_5/\signature_weight_t_reg[11,0][15] )}}  -suppress 
set_msg_config  -ruleid {8}  -id {Common 17-349}  -string {{INFO: [Common 17-349] Got license for feature 'Synthesis' and/or device 'xc7z045'}}  -suppress 
set_msg_config  -ruleid {80}  -id {Common 17-14}  -string {{INFO: [Common 17-14] Message 'Synth 8-327' appears 100 times and further instances of the messages will be disabled. Use the Tcl command set_msg_config to change the current settings.}}  -suppress 
set_msg_config  -ruleid {81}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (flag_t_reg[28]) is unused and will be removed from module neuro_bio.}}  -suppress 
set_msg_config  -ruleid {82}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[19,2]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {83}  -string {{Running DRC as a precondition to command place_design}}  -suppress 
set_msg_config  -ruleid {84}  -id {Place 30-68}  -string {{ERROR: [Place 30-68] Instance SWM_neurons[0,0][-3]_INST_0 (OBUF) is not placed}}  -suppress 
set_msg_config  -ruleid {85}  -id {HDL 9-1061}  -string {{INFO: [HDL 9-1061] Parsing VHDL file "/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/float_pkg_c.vhd" into library neuronal [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/float_pkg_c.vhd:1]}}  -suppress 
set_msg_config  -ruleid {86}  -id {Synth 8-638}  -string {{INFO: [Synth 8-638] synthesizing module 'spatial_working_memory' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:39]}}  -suppress 
set_msg_config  -ruleid {87}  -id {Synth 8-613}  -string {{WARNING: [Synth 8-613] shared variable will be implemented as local to architecture [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/tree_reduction.vhd:35]}}  -suppress 
set_msg_config  -ruleid {88}  -id {Synth 8-256}  -string {{INFO: [Synth 8-256] done synthesizing module 'top_level' (4#1) [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/top_level.vhd:39]}}  -suppress 
set_msg_config  -ruleid {89}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design spatial_working_memory has unconnected port azimuth_neurons[16][12]}}  -suppress 
set_msg_config  -ruleid {9}  -id {Synth 8-256}  -string {{INFO: [Synth 8-256] done synthesizing module 'neuro_bio' (1#1) [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd:30]}}  -suppress 
set_msg_config  -ruleid {90}  -string {{Processing XDC Constraints}}  -suppress 
set_msg_config  -ruleid {91}  -id {Synth 8-5545}  -string {{INFO: [Synth 8-5545] ROM "flag_t" won't be mapped to RAM because address size (31) is larger than maximum supported(25)}}  -suppress 
set_msg_config  -ruleid {92}  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'signature_weight_t_reg[1,0]' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:150]}}  -suppress 
set_msg_config  -ruleid {93}  -id {Synth 8-223}  -string {{INFO: [Synth 8-223] decloning instance 'Concurrent_loop_for_pixels[0].U1' (neuro_bio) to 'Concurrent_loop_for_pixels[4].U1'}}  -suppress 
set_msg_config  -ruleid {94}  -id {Synth 8-3886}  -string {{INFO: [Synth 8-3886] merging instance 'U3i_5/signature_weight_t_reg[17,0][-5]' (LD) to 'U3i_5/signature_weight_t_reg[17,0][15]'}}  -suppress 
set_msg_config  -ruleid {95}  -id {Synth 8-3333}  -string {{INFO: [Synth 8-3333] propagating constant 0 across sequential element (U3i_5/\signature_weight_t_reg[1,2][15] )}}  -suppress 
set_msg_config  -ruleid {96}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (flag_t_reg[27]) is unused and will be removed from module neuro_bio.}}  -suppress 
set_msg_config  -ruleid {97}  -id {Common 17-14}  -string {{INFO: [Common 17-14] Message 'Synth 8-3886' appears 100 times and further instances of the messages will be disabled. Use the Tcl command set_msg_config to change the current settings.}}  -suppress 
set_msg_config  -ruleid {98}  -id {Synth 8-3352}  -string {{CRITICAL WARNING: [Synth 8-3352] multi-driven net Q with 1st driver pin 'SWM_neurons_flag_learning_reg[19,1]/Q' [/users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd:172]}}  -suppress 
set_msg_config  -ruleid {99}  -string {{Starting Placer Task}}  -suppress 
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.cache/wt [current_project]
set_property parent.project_path /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc706:part0:1.3 [current_project]
set_property ip_output_repo /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library neuronal {
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/MATH_REAL.vhd
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_float_types_c.vhd
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_pkg_c.vhd
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/imports/ieee/float_pkg_c.vhd
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/package_type.vhd
}
read_vhdl -library xil_defaultlib {
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/new/spatial_working_memory.vhd
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/tree_reduction.vhd
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd
  /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/top_level.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/constrs_1/new/top_constraint.xdc
set_property used_in_implementation false [get_files /users/tareelou/neural_network_sfixed_V2/neural_network_sfixed.srcs/constrs_1/new/top_constraint.xdc]


synth_design -top top_level -part xc7z045ffg900-2


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
